import type { DdMenu, DdModifierGroup } from "./types";

const sizeGroup = (prefix: string): DdModifierGroup => ({
  id: `${prefix}_size`,
  name: "Size",
  min: 1,
  max: 1,
  required: true,
  options: [
    {
      id: `${prefix}_reg`,
      name: "Regular",
      priceCents: 0,
      available: true,
      isDefault: true,
    },
    {
      id: `${prefix}_lg`,
      name: "Large",
      priceCents: 200,
      available: true,
    },
  ],
});

const proteinGroup = (prefix: string): DdModifierGroup => ({
  id: `${prefix}_protein`,
  name: "Protein",
  min: 1,
  max: 1,
  required: true,
  options: [
    {
      id: `${prefix}_chicken`,
      name: "Chicken",
      priceCents: 0,
      available: true,
      isDefault: true,
    },
    {
      id: `${prefix}_steak`,
      name: "Steak",
      priceCents: 200,
      available: true,
    },
    {
      id: `${prefix}_sofritas`,
      name: "Sofritas",
      priceCents: 0,
      available: true,
    },
    {
      id: `${prefix}_double`,
      name: "Double protein",
      priceCents: 350,
      available: true,
    },
  ],
});

const extrasGroup = (prefix: string): DdModifierGroup => ({
  id: `${prefix}_extras`,
  name: "Add-ons",
  min: 0,
  max: 4,
  required: false,
  options: [
    {
      id: `${prefix}_guac`,
      name: "Guacamole",
      priceCents: 295,
      available: true,
    },
    {
      id: `${prefix}_queso`,
      name: "Queso",
      priceCents: 195,
      available: true,
    },
    {
      id: `${prefix}_extra_salsa`,
      name: "Extra salsa",
      priceCents: 0,
      available: true,
    },
    {
      id: `${prefix}_no_onion`,
      name: "No onion",
      priceCents: 0,
      available: true,
    },
  ],
});

/** Rich mock menus — modifiers, calories, tags (in-app picker, not iframe). */
export const MOCK_MENUS: Record<string, DdMenu> = {
  dd_chipotle_01: {
    storeId: "dd_chipotle_01",
    storeName: "Chipotle",
    storeUrl: "https://www.doordash.com",
    categories: ["Bowls", "Burritos", "Sides", "Drinks"],
    items: [
      {
        id: "ch_bowl_build",
        name: "Build Your Bowl",
        description: "Rice, beans, protein, salsas — customize everything",
        priceCents: 1095,
        category: "Bowls",
        available: true,
        popular: true,
        calories: 740,
        tags: ["customizable", "gluten-conscious"],
        modifierGroups: [
          sizeGroup("ch_bowl"),
          proteinGroup("ch_bowl"),
          extrasGroup("ch_bowl"),
        ],
      },
      {
        id: "ch_burrito",
        name: "Burrito",
        description: "Flour tortilla, fillings of your choice",
        priceCents: 1045,
        category: "Burritos",
        available: true,
        calories: 900,
        spicyLevel: 1,
        modifierGroups: [proteinGroup("ch_bur"), extrasGroup("ch_bur")],
      },
      {
        id: "ch_chips_guac",
        name: "Chips & Guac",
        priceCents: 495,
        category: "Sides",
        available: true,
        calories: 770,
        modifierGroups: [],
      },
      {
        id: "ch_drink",
        name: "Fountain Drink",
        priceCents: 295,
        category: "Drinks",
        available: true,
        modifierGroups: [sizeGroup("ch_drink")],
      },
    ],
  },
  dd_sweetgreen_01: {
    storeId: "dd_sweetgreen_01",
    storeName: "Sweetgreen",
    storeUrl: "https://www.doordash.com",
    categories: ["Bowls", "Warm Plates", "Sides"],
    items: [
      {
        id: "sg_harvest",
        name: "Harvest Bowl",
        description: "Roasted chicken, sweet potatoes, apples, goat cheese",
        priceCents: 1450,
        category: "Bowls",
        available: true,
        popular: true,
        calories: 640,
        tags: ["contains dairy"],
        modifierGroups: [
          {
            id: "sg_harvest_dressing",
            name: "Dressing",
            min: 1,
            max: 1,
            required: true,
            options: [
              {
                id: "sg_balsamic",
                name: "Balsamic vinaigrette",
                priceCents: 0,
                available: true,
                isDefault: true,
              },
              {
                id: "sg_miso",
                name: "Miso sesame",
                priceCents: 0,
                available: true,
              },
              {
                id: "sg_none",
                name: "No dressing",
                priceCents: 0,
                available: true,
              },
            ],
          },
          {
            id: "sg_harvest_add",
            name: "Add-ons",
            min: 0,
            max: 3,
            required: false,
            options: [
              {
                id: "sg_avo",
                name: "Avocado",
                priceCents: 225,
                available: true,
              },
              {
                id: "sg_extra_chicken",
                name: "Extra chicken",
                priceCents: 350,
                available: true,
              },
            ],
          },
        ],
      },
      {
        id: "sg_crispy_rice",
        name: "Crispy Rice Bowl",
        priceCents: 1550,
        category: "Bowls",
        available: true,
        spicyLevel: 2,
        calories: 710,
        modifierGroups: [],
      },
      {
        id: "sg_hot_chicken",
        name: "Hot Chicken Plate",
        priceCents: 1495,
        category: "Warm Plates",
        available: false,
        spicyLevel: 3,
        tags: ["sold out"],
        modifierGroups: [],
      },
    ],
  },
  dd_thaibasil_01: {
    storeId: "dd_thaibasil_01",
    storeName: "Thai Basil",
    storeUrl: "https://www.doordash.com",
    categories: ["Noodles", "Curries", "Apps"],
    items: [
      {
        id: "tb_pad_thai",
        name: "Pad Thai",
        description: "Rice noodles, egg, peanuts, tamarind",
        priceCents: 1599,
        category: "Noodles",
        available: true,
        popular: true,
        spicyLevel: 1,
        calories: 820,
        modifierGroups: [
          {
            id: "tb_pt_protein",
            name: "Protein",
            min: 1,
            max: 1,
            required: true,
            options: [
              {
                id: "tb_tofu",
                name: "Tofu",
                priceCents: 0,
                available: true,
                isDefault: true,
              },
              {
                id: "tb_chicken",
                name: "Chicken",
                priceCents: 200,
                available: true,
              },
              {
                id: "tb_shrimp",
                name: "Shrimp",
                priceCents: 350,
                available: true,
              },
            ],
          },
          {
            id: "tb_pt_spice",
            name: "Spice level",
            min: 1,
            max: 1,
            required: true,
            options: [
              {
                id: "tb_mild",
                name: "Mild",
                priceCents: 0,
                available: true,
                isDefault: true,
              },
              {
                id: "tb_med",
                name: "Medium",
                priceCents: 0,
                available: true,
              },
              {
                id: "tb_hot",
                name: "Hot",
                priceCents: 0,
                available: true,
              },
            ],
          },
        ],
      },
      {
        id: "tb_green_curry",
        name: "Green Curry",
        priceCents: 1699,
        category: "Curries",
        available: true,
        spicyLevel: 2,
        modifierGroups: [
          {
            id: "tb_gc_rice",
            name: "Rice",
            min: 0,
            max: 1,
            required: false,
            options: [
              {
                id: "tb_white",
                name: "White rice",
                priceCents: 200,
                available: true,
              },
              {
                id: "tb_brown",
                name: "Brown rice",
                priceCents: 250,
                available: true,
              },
            ],
          },
        ],
      },
      {
        id: "tb_spring_rolls",
        name: "Spring Rolls",
        priceCents: 799,
        category: "Apps",
        available: true,
        modifierGroups: [],
      },
    ],
  },
  dd_cava_01: {
    storeId: "dd_cava_01",
    storeName: "CAVA",
    storeUrl: "https://www.doordash.com",
    categories: ["Bowls", "Pitas"],
    items: [
      {
        id: "cv_greens_grain",
        name: "Greens & Grains Bowl",
        priceCents: 1299,
        category: "Bowls",
        available: true,
        popular: true,
        calories: 580,
        modifierGroups: [
          {
            id: "cv_dip",
            name: "Dips",
            min: 1,
            max: 2,
            required: true,
            options: [
              {
                id: "cv_hummus",
                name: "Hummus",
                priceCents: 0,
                available: true,
                isDefault: true,
              },
              {
                id: "cv_harissa",
                name: "Harissa",
                priceCents: 0,
                available: true,
              },
              {
                id: "cv_tzatziki",
                name: "Tzatziki",
                priceCents: 0,
                available: true,
              },
            ],
          },
        ],
      },
      {
        id: "cv_spicy_lamb",
        name: "Spicy Lamb Pita",
        priceCents: 1399,
        category: "Pitas",
        available: true,
        spicyLevel: 2,
        modifierGroups: [],
      },
    ],
  },
  dd_shake_01: {
    storeId: "dd_shake_01",
    storeName: "Shake Shack",
    storeUrl: "https://www.doordash.com",
    categories: ["Burgers", "Shakes", "Fries"],
    items: [
      {
        id: "ss_shackburger",
        name: "ShackBurger",
        description: "Cheese, lettuce, tomato, ShackSauce",
        priceCents: 899,
        category: "Burgers",
        available: true,
        popular: true,
        calories: 550,
        modifierGroups: [
          sizeGroup("ss_burg"),
          {
            id: "ss_burg_style",
            name: "Style",
            min: 0,
            max: 3,
            required: false,
            options: [
              {
                id: "ss_no_tomato",
                name: "No tomato",
                priceCents: 0,
                available: true,
              },
              {
                id: "ss_extra_sauce",
                name: "Extra ShackSauce",
                priceCents: 0,
                available: true,
              },
              {
                id: "ss_bacon",
                name: "Add bacon",
                priceCents: 250,
                available: true,
              },
            ],
          },
        ],
      },
      {
        id: "ss_smoke",
        name: "SmokeShack",
        priceCents: 1099,
        category: "Burgers",
        available: true,
        calories: 650,
        modifierGroups: [sizeGroup("ss_smoke")],
      },
      {
        id: "ss_fries",
        name: "Crinkle-Cut Fries",
        priceCents: 449,
        category: "Fries",
        available: true,
        modifierGroups: [sizeGroup("ss_fries")],
      },
      {
        id: "ss_shake",
        name: "Hand-Spun Shake",
        priceCents: 599,
        category: "Shakes",
        available: true,
        modifierGroups: [
          {
            id: "ss_flavor",
            name: "Flavor",
            min: 1,
            max: 1,
            required: true,
            options: [
              {
                id: "ss_vanilla",
                name: "Vanilla",
                priceCents: 0,
                available: true,
                isDefault: true,
              },
              {
                id: "ss_chocolate",
                name: "Chocolate",
                priceCents: 0,
                available: true,
              },
              {
                id: "ss_strawberry",
                name: "Strawberry",
                priceCents: 50,
                available: true,
              },
            ],
          },
        ],
      },
    ],
  },
};
